"""
Umang AI - Database Models
Ye file batati hai database mein kaunse tables honge aur unke columns kya hain.
"""

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Time, Boolean, Date
from sqlalchemy.sql import func
from database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    phone = Column(String, unique=True, nullable=True)
    language = Column(String, default="hindi")
    family_email = Column(String, nullable=True)
    last_alert_sent_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Conversation(Base):
    """Stores individual messages exchanged between a user and the assistant,
    enabling persistent, context-aware conversation history."""

    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    role = Column(String, nullable=False)
    message = Column(String, nullable=False)
    emotion = Column(String, nullable=True)   # Detected emotional tone (user messages only)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Reminder(Base):
    """Represents a recurring daily reminder (medicine, routine task, etc.)
    that Umang proactively brings up in conversation when due."""

    __tablename__ = "reminders"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    reminder_time = Column(Time, nullable=False)
    frequency = Column(String, default="daily")
    last_acknowledged_date = Column(Date, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class PendingCheckin(Base):
    """A scheduled proactive check-in message generated by the background
    scheduler (e.g. morning / evening greetings). Delivered to the user
    the next time they open the app, then dismissed."""

    __tablename__ = "pending_checkins"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    message = Column(String, nullable=False)   # The check-in message text
    checkin_type = Column(String, nullable=False)  # "morning" | "evening"
    is_delivered = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())